# Generated by Django 3.2.6 on 2021-08-21 09:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n03_001', models.CharField(blank=True, max_length=50)),
                ('n03_002', models.CharField(blank=True, max_length=50)),
                ('n03_003', models.CharField(blank=True, max_length=50)),
                ('n03_004', models.CharField(blank=True, max_length=50)),
                ('n03_007', models.CharField(blank=True, max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name': '行政区域データ',
                'verbose_name_plural': '行政区域データ',
            },
        ),
        migrations.CreateModel(
            name='Busstop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p11_001', models.CharField(blank=True, max_length=256)),
                ('p11_002', models.CharField(blank=True, max_length=256)),
                ('p11_003_1', models.CharField(blank=True, max_length=256)),
                ('p11_003_2', models.CharField(blank=True, max_length=256)),
                ('p11_003_3', models.CharField(blank=True, max_length=256)),
                ('p11_003_4', models.CharField(blank=True, max_length=256)),
                ('p11_003_5', models.CharField(blank=True, max_length=256)),
                ('p11_003_6', models.CharField(blank=True, max_length=256)),
                ('p11_003_7', models.CharField(blank=True, max_length=256)),
                ('p11_003_8', models.CharField(blank=True, max_length=256)),
                ('p11_003_9', models.CharField(blank=True, max_length=256)),
                ('p11_003_10', models.CharField(blank=True, max_length=256)),
                ('p11_003_11', models.CharField(blank=True, max_length=256)),
                ('p11_003_12', models.CharField(blank=True, max_length=256)),
                ('p11_003_13', models.CharField(blank=True, max_length=256)),
                ('p11_003_14', models.CharField(blank=True, max_length=256)),
                ('p11_003_15', models.CharField(blank=True, max_length=256)),
                ('p11_003_16', models.CharField(blank=True, max_length=256)),
                ('p11_003_17', models.CharField(blank=True, max_length=256)),
                ('p11_003_18', models.CharField(blank=True, max_length=256)),
                ('p11_003_19', models.CharField(blank=True, max_length=256)),
                ('p11_004_1', models.CharField(blank=True, max_length=256)),
                ('p11_004_2', models.CharField(blank=True, max_length=256)),
                ('p11_004_3', models.CharField(blank=True, max_length=256)),
                ('p11_004_4', models.CharField(blank=True, max_length=256)),
                ('p11_004_5', models.CharField(blank=True, max_length=256)),
                ('p11_004_6', models.CharField(blank=True, max_length=256)),
                ('p11_004_7', models.CharField(blank=True, max_length=256)),
                ('p11_004_8', models.CharField(blank=True, max_length=256)),
                ('p11_004_9', models.CharField(blank=True, max_length=256)),
                ('p11_004_10', models.CharField(blank=True, max_length=256)),
                ('p11_004_11', models.CharField(blank=True, max_length=256)),
                ('p11_004_12', models.CharField(blank=True, max_length=256)),
                ('p11_004_13', models.CharField(blank=True, max_length=256)),
                ('p11_004_14', models.CharField(blank=True, max_length=256)),
                ('p11_004_15', models.CharField(blank=True, max_length=256)),
                ('p11_004_16', models.CharField(blank=True, max_length=256)),
                ('p11_004_17', models.CharField(blank=True, max_length=256)),
                ('p11_004_18', models.CharField(blank=True, max_length=256)),
                ('p11_004_19', models.CharField(blank=True, max_length=256)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'バス停留所データ',
                'verbose_name_plural': 'バス停留所データ',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p02_001', models.CharField(blank=True, max_length=50)),
                ('p02_002', models.CharField(blank=True, max_length=50)),
                ('p02_003', models.CharField(blank=True, max_length=50)),
                ('p02_004', models.CharField(blank=True, max_length=50)),
                ('p02_005', models.CharField(blank=True, max_length=50)),
                ('p02_006', models.CharField(blank=True, max_length=50)),
                ('p02_007', models.CharField(blank=True, max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': '公共施設データ',
                'verbose_name_plural': '公共施設データ',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a27_001', models.CharField(blank=True, max_length=50)),
                ('a27_002', models.CharField(blank=True, max_length=50)),
                ('a27_003', models.CharField(blank=True, max_length=50)),
                ('a27_004', models.CharField(blank=True, max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': '小学校区データ',
                'verbose_name_plural': '小学校区データ',
            },
        ),
    ]
